export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ADDED_EMPLOYEES = "SET_ADDED_EMPLOYEES";
export const SET_ADDED_FARMERS = "SET_ADDED_FARMERS"
export const SET_FARMER_DETAILS = "SET_FARMER_DETAILS"
export const SET_LAND_DETAILS = "SET_LAND_DETAILS"
export const SET_CROP_DETAILS = "SET_CROP_DETAILS"
export const SET_GARDEN_DETAILS = "SET_GARDEN_DETAILS"
export const SET_LIVESTOCK_DETAILS = "SET_LIVESTOCK_DETAILS"
export const SET_LABOUR_DETAILS = "SET_LABOUR_DETAILS"
export const SET_MACHINE_DETAILS = "SET_MACHINE_DETAILS"


